import { Deal } from "./database.types";

export interface DealWithSource extends Deal {
  source_url?: string;
  source_platform?: string;
}

let _cache: DealWithSource[] | null = null;

/**
 * Load all deals from the static JSON file (generated by the scraper).
 * Cached after first load.
 */
export async function loadAllDeals(): Promise<DealWithSource[]> {
  if (_cache) return _cache;

  try {
    const res = await fetch("/data/deals.json");
    if (!res.ok) return [];
    const data = await res.json();
    _cache = Array.isArray(data) ? data : [];
    return _cache;
  } catch {
    return [];
  }
}

/**
 * Find a single deal by ID from the static data.
 */
export async function findDealById(
  id: string
): Promise<DealWithSource | null> {
  const deals = await loadAllDeals();
  return deals.find((d) => d.id === id) || null;
}

/**
 * Find deals matching make/model (for "similar deals").
 */
export async function findSimilarDeals(
  make: string,
  model: string,
  excludeId: string,
  limit: number = 5
): Promise<DealWithSource[]> {
  const deals = await loadAllDeals();
  return deals
    .filter(
      (d) =>
        d.vehicle_make === make &&
        d.vehicle_model === model &&
        d.id !== excludeId
    )
    .slice(0, limit);
}

/**
 * Filter deals client-side.
 */
export function filterDeals(
  deals: DealWithSource[],
  filters: {
    make?: string;
    model?: string;
    province?: string;
    year?: string;
    dealType?: string;
    grade?: string;
  }
): DealWithSource[] {
  return deals.filter((d) => {
    if (filters.make && d.vehicle_make !== filters.make) return false;
    if (
      filters.model &&
      !d.vehicle_model.toLowerCase().includes(filters.model.toLowerCase())
    )
      return false;
    if (filters.province && d.province !== filters.province) return false;
    if (filters.year && d.vehicle_year !== parseInt(filters.year)) return false;
    if (filters.dealType && d.deal_type !== filters.dealType) return false;
    if (filters.grade && d.overall_grade !== filters.grade) return false;
    return true;
  });
}

/**
 * Compute aggregate stats from a deal array.
 */
export function computeStats(deals: DealWithSource[]) {
  const avg = (arr: number[]) =>
    arr.length > 0
      ? Math.round((arr.reduce((a, b) => a + b, 0) / arr.length) * 10) / 10
      : 0;

  const aprs = deals.map((d) => d.apr).filter((v): v is number => v != null);
  const residuals = deals
    .map((d) => d.residual_percent)
    .filter((v): v is number => v != null);
  const discounts = deals
    .map((d) => d.discount_percent)
    .filter((v): v is number => v != null);

  return {
    totalDeals: deals.length,
    avgApr: avg(aprs),
    avgResidual: avg(residuals),
    avgDiscount: avg(discounts),
  };
}
